"use client";

import { useState } from "react";
import {
  CheckCircle,
  AlertTriangle,
  XCircle,
  ChevronDown,
  ChevronUp,
  Copy,
  Download,
  BookOpen,
  Shield,
  ArrowRight,
  Scale,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

// Props:
// result = {
//   summary: string,
//   rights: string[],
//   nextSteps: string[],
//   lawsCited: string[],
//   category: string,
//   riskLevel: "Low" | "Medium" | "High",
//   language: "ne" | "hi" | "en",
// }

const RISK_CONFIG = {
  Low: {
    color: "bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-300",
    icon: CheckCircle,
    iconColor: "text-green-500",
    label: "Low Risk",
    desc: "This document appears standard and low risk.",
  },
  Medium: {
    color: "bg-yellow-100 text-yellow-700 dark:bg-yellow-900 dark:text-yellow-300",
    icon: AlertTriangle,
    iconColor: "text-yellow-500",
    label: "Medium Risk",
    desc: "Some clauses may need attention. Review carefully.",
  },
  High: {
    color: "bg-red-100 text-red-700 dark:bg-red-900 dark:text-red-300",
    icon: XCircle,
    iconColor: "text-red-500",
    label: "High Risk",
    desc: "This document has serious concerns. Consult a lawyer.",
  },
};

const SECTION_LABELS = {
  summary: { ne: "सारांश", hi: "सारांश", en: "Summary" },
  rights: { ne: "तपाईंका अधिकारहरू", hi: "आपके अधिकार", en: "Your Rights" },
  nextSteps: { ne: "अर्को कदमहरू", hi: "अगले कदम", en: "Next Steps" },
  laws: { ne: "कानुनी सन्दर्भ", hi: "कानूनी संदर्भ", en: "Laws Referenced" },
};

export default function LegalSummary({ result }) {
  const [collapsed, setCollapsed] = useState({
    summary: false,
    rights: false,
    nextSteps: false,
    laws: false,
  });

  if (!result) return null;

  const { summary, rights, nextSteps, lawsCited, category, riskLevel, language = "ne" } = result;
  const risk = RISK_CONFIG[riskLevel] || RISK_CONFIG["Low"];
  const RiskIcon = risk.icon;
  const labels = (key) => SECTION_LABELS[key][language] || SECTION_LABELS[key]["en"];

  const toggleSection = (section) => {
    setCollapsed((prev) => ({ ...prev, [section]: !prev[section] }));
  };

  const handleCopyAll = () => {
    const text = `
=== LegalSaathi Analysis ===

[${labels("summary")}]
${summary}

[${labels("rights")}]
${rights.map((r, i) => `${i + 1}. ${r}`).join("\n")}

[${labels("nextSteps")}]
${nextSteps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

[${labels("laws")}]
${lawsCited.join(", ")}

Category: ${category} | Risk: ${riskLevel}
Generated by LegalSaathi 🇳🇵
    `.trim();

    navigator.clipboard.writeText(text);
    toast.success("Full analysis copied to clipboard!");
  };

  const handleDownload = () => {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8" />
      <title>LegalSaathi Analysis Report</title>
      <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; }
        .header { border-bottom: 3px solid #2563eb; padding-bottom: 16px; margin-bottom: 24px; }
        .logo { color: #2563eb; font-size: 24px; font-weight: bold; }
        .meta { color: #666; font-size: 13px; margin-top: 6px; }
        .risk-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: bold; margin-left: 8px; }
        .risk-Low { background: #dcfce7; color: #166534; }
        .risk-Medium { background: #fef9c3; color: #854d0e; }
        .risk-High { background: #fee2e2; color: #991b1b; }
        .section { margin-bottom: 24px; padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; }
        .section-title { font-size: 16px; font-weight: bold; color: #2563eb; margin-bottom: 12px; }
        .section p { color: #374151; line-height: 1.7; margin: 0; }
        ul, ol { padding-left: 20px; margin: 0; }
        li { color: #374151; line-height: 1.8; margin-bottom: 4px; }
        .law-badge { display: inline-block; background: #eff6ff; color: #1d4ed8; border: 1px solid #bfdbfe; padding: 3px 10px; border-radius: 12px; font-size: 12px; margin: 3px; }
        .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; text-align: center; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo">⚖️ LegalSaathi</div>
        <div class="meta">
          Analysis Report · ${new Date().toLocaleDateString("en-NP")}
          · Category: <strong>${category}</strong>
          <span class="risk-badge risk-${riskLevel}">Risk: ${riskLevel}</span>
        </div>
      </div>
      <div class="section">
        <div class="section-title">📄 Document Summary</div>
        <p>${summary}</p>
      </div>
      <div class="section">
        <div class="section-title">⚖️ Your Rights</div>
        <ul>${rights.map((r) => `<li>${r}</li>`).join("")}</ul>
      </div>
      <div class="section">
        <div class="section-title">🔜 Recommended Next Steps</div>
        <ol>${nextSteps.map((s) => `<li>${s}</li>`).join("")}</ol>
      </div>
      <div class="section">
        <div class="section-title">📚 Laws Referenced</div>
        <div>${lawsCited.map((law) => `<span class="law-badge">📚 ${law}</span>`).join("")}</div>
      </div>
      <div class="footer">
        Generated by LegalSaathi 🇳🇵 · न्याय सबैको लागि · For legal advice, consult a qualified lawyer.
      </div>
    </body>
    </html>
  `;

  const blob = new Blob([htmlContent], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const printWindow = window.open(url, "_blank");
  printWindow.onload = () => {
    printWindow.print();
    URL.revokeObjectURL(url);
  };
  toast.success("Opening print dialog — Save as PDF!");
};
  return (
    <div className="space-y-5">

      {/* Result Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl legal-gradient flex items-center justify-center">
            <Scale className="w-5 h-5 text-white" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-foreground">Analysis Complete</h2>
            <p className="text-xs text-muted-foreground">Powered by LegalSaathi AI</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant="outline" className="text-xs">{category}</Badge>
          <Badge className={`text-xs ${risk.color}`}>
            <RiskIcon className={`w-3 h-3 mr-1 ${risk.iconColor}`} />
            {risk.label}
          </Badge>
        </div>
      </div>

      {/* Risk Banner */}
      <div className={`rounded-xl px-4 py-3 flex items-center gap-3 ${risk.color}`}>
        <RiskIcon className={`w-5 h-5 shrink-0 ${risk.iconColor}`} />
        <p className="text-sm font-medium">{risk.desc}</p>
      </div>

      {/* Summary Section */}
      <Card className="border border-border">
        <CardHeader
          className="pb-2 cursor-pointer select-none"
          onClick={() => toggleSection("summary")}
        >
          <div className="flex items-center justify-between">
            <CardTitle className="text-base flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-primary" />
              📄 {labels("summary")}
            </CardTitle>
            {collapsed.summary ? (
              <ChevronDown className="w-4 h-4 text-muted-foreground" />
            ) : (
              <ChevronUp className="w-4 h-4 text-muted-foreground" />
            )}
          </div>
        </CardHeader>
        {!collapsed.summary && (
          <CardContent>
            <p className="text-muted-foreground leading-relaxed text-sm">{summary}</p>
          </CardContent>
        )}
      </Card>

      {/* Rights Section */}
      <Card className="border border-border">
        <CardHeader
          className="pb-2 cursor-pointer select-none"
          onClick={() => toggleSection("rights")}
        >
          <div className="flex items-center justify-between">
            <CardTitle className="text-base flex items-center gap-2">
              <Shield className="w-4 h-4 text-primary" />
              ⚖️ {labels("rights")}
            </CardTitle>
            {collapsed.rights ? (
              <ChevronDown className="w-4 h-4 text-muted-foreground" />
            ) : (
              <ChevronUp className="w-4 h-4 text-muted-foreground" />
            )}
          </div>
        </CardHeader>
        {!collapsed.rights && (
          <CardContent>
            <ul className="space-y-3">
              {rights.map((right, i) => (
                <li key={i} className="flex items-start gap-3">
                  <CheckCircle className="w-4 h-4 text-green-500 mt-0.5 shrink-0" />
                  <span className="text-sm text-muted-foreground leading-relaxed">
                    {right}
                  </span>
                </li>
              ))}
            </ul>
          </CardContent>
        )}
      </Card>

      {/* Next Steps Section */}
      <Card className="border border-border">
        <CardHeader
          className="pb-2 cursor-pointer select-none"
          onClick={() => toggleSection("nextSteps")}
        >
          <div className="flex items-center justify-between">
            <CardTitle className="text-base flex items-center gap-2">
              <ArrowRight className="w-4 h-4 text-primary" />
              🔜 {labels("nextSteps")}
            </CardTitle>
            {collapsed.nextSteps ? (
              <ChevronDown className="w-4 h-4 text-muted-foreground" />
            ) : (
              <ChevronUp className="w-4 h-4 text-muted-foreground" />
            )}
          </div>
        </CardHeader>
        {!collapsed.nextSteps && (
          <CardContent>
            <ol className="space-y-3">
              {nextSteps.map((step, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span className="w-6 h-6 rounded-full bg-primary text-primary-foreground text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">
                    {i + 1}
                  </span>
                  <span className="text-sm text-muted-foreground leading-relaxed">
                    {step}
                  </span>
                </li>
              ))}
            </ol>
          </CardContent>
        )}
      </Card>

      {/* Laws Cited Section */}
      <Card className="border border-border">
        <CardHeader
          className="pb-2 cursor-pointer select-none"
          onClick={() => toggleSection("laws")}
        >
          <div className="flex items-center justify-between">
            <CardTitle className="text-base flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-primary" />
              📚 {labels("laws")}
            </CardTitle>
            {collapsed.laws ? (
              <ChevronDown className="w-4 h-4 text-muted-foreground" />
            ) : (
              <ChevronUp className="w-4 h-4 text-muted-foreground" />
            )}
          </div>
        </CardHeader>
        {!collapsed.laws && (
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {lawsCited.map((law, i) => (
                <Badge key={i} variant="secondary" className="text-xs py-1 px-3">
                  📚 {law}
                </Badge>
              ))}
            </div>
          </CardContent>
        )}
      </Card>

      {/* Action Buttons */}
      <div className="flex items-center gap-3 flex-wrap pt-1">
        <Button
          variant="outline"
          size="sm"
          onClick={handleCopyAll}
          className="gap-2"
        >
          <Copy className="w-4 h-4" />
          Copy Full Analysis
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={handleDownload}
          className="gap-2"
        >
          <Download className="w-4 h-4" />
          Download as PDF
        </Button>
      </div>

    </div>
  );
}